"use client";

//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Remove this line as metadata can't be defined in a client component
// const metadata: Metadata = { ... };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      navigator.serviceWorker.register('/service-worker.js')
        .then(registration => {
          console.log('Service Worker registered successfully:', registration.scope);
        })
        .catch(error => {
          console.error('Service Worker registration failed:', error);
        });
    }
  }, []); 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
<<<<<<< HEAD

=======
>>>>>>> af0fcc9 (changes done)
// Move metadata export to a separate file or remove
// export const metadata: Metadata = {
//   title: "KAKSHA",
//   description: "Generated by some berozgaars",
<<<<<<< HEAD
// };
=======
// };
>>>>>>> af0fcc9 (changes done)
